environment = "test"

[http]

[[http.server]]
listen = ["80"]
serverName = ["mail-test.sdkwork.com", "mail-test.birdcoder.com", "mail-test.dtupay.com", "mail-test.sdkwork.cn", "mail-test.birdcoder.cn", "mail-test.dtupay.cn", "mail-test.skubc.com", "mail-test.skubc.cn", "mail-test.zowalk.com", "mail-test.zowalk.cn", "mail-test.offer86.com", "mail-test.offer86.cn", "mail-test.86offer.com", "mail-test.86offer.cn"]
include = ["snippets/gateway-locations.nonproduction.conf"]

